In [ ]:
## 파이썬을 활용한 데이터 분석과 이미치 처리
## 1차원을 vector 2차원을 matrix 3차원이상 tensor
## 1차원 축 axis 0 2차원 축 axis 1 3차원축 axis2

In [68]:
## numpy 실습
import numpy as np

# 0부터 3까지 배열 만들기 
array1 = np.arange(4)
print(array1)

array2 = np.zeros((4,4), dtype=float)
print(array2)

# 0부터 9까지 랜덤하기 초기화
array4 = np.random.randint(0,10, (3,3))## 0~9 랜덤 -1 해야함
print(array4)

## 평균 0이고 , 표준편차가 1인 표준 정규를 띄는 배열 
array5 = np.random.normal( 0, 1 , (3,3))
print(array5)

## 배열합치기
array6 = np.array([1,2,3])
array7 = np.array([4,5,6])
array8 = np.concatenate([array6, array7])
print(array8.shape)

## 1차원 배열을 2차원으로 재구성
a9 = np.arange(4)
a10 = a9.reshape((2,2))
print(a10)

## 배열 합치기 
a11 = np.arange(4).reshape(1,4) ## 1행 4열
a12 = np.arange(8).reshape(2,4) ## 2행 4열
a13 = np.concatenate([a11, a12], axis=0)

print(a13)

## 배열 나누기


left, right = np.split(a12, [2], axis=1) ## 2차원
print(left.shape)
print(right.shape)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[8 9 5]
 [8 9 9]
 [6 4 6]]
[[-0.58535976 -1.74035965  0.64701258]
 [ 1.77400832 -0.10024475 -0.65792602]
 [-1.08286949 -1.7895015   0.64318925]]
(6,)
[[0 1]
 [2 3]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)
